
export const stocksToTrack = [
    //"AXP",
    // "AMGN",
    // "AAPL",
    // "BA",
    // "CAT",
    //"CSCO",
    // "GS"
    // "HD",
    //  "HON",
    //  "IBM",
    //  "INTC",
    // "KO",
    // "JPM",
    // "MCD",
    // "MMM",
    // "MRK",
    // "MSFT",
    // "NKE",
    // "PG",
    // "TRV",
    // "UNH",
    // "CRM",
    // "VZ",
    // "V",
    // "WBA",
    // "WMT",
    // "DIS",
]

export const fields = [
    'companyName',
    'description',
    'industry',
    "symbol",
    "PEG",
    'bookValue',
    'divPerShare',
    'divYield',
    'EPS',
    'ROA',
    'ROE',
    'quarterEarningsGrowth',
    'quarterRevenueGrowth',
    'targetPrice',
    'trailingPE',
    'forwardPE' ,
    'priceToSales',
    'priceToBook',
    'yearlyHigh',
    'yearlyLow',
    'fiftyDayMovingAvg',
    'twoHundredDayMovingAvg',
]

export const metrics = [
    "Name",
    "Description",
    "Industry",
    "Symbol",
    "PEGRatio",
    "BookValue",
    "DividendPerShare",
    "DividendYield",
    "EPS",
    "ReturnOnAssetsTTM",
    "ReturnOnEquityTTM",
    "QuarterlyEarningsGrowthYOY",
    "QuarterlyRevenueGrowthYOY",
    "AnalystTargetPrice",
    "TrailingPE",
    "ForwardPE",
    "PriceToSalesRatioTTM",
    "PriceToBookRatio",
    "52WeekHigh",
    "52WeekLow",
    "50DayMovingAverage" ,
    "200DayMovingAverage",
]

export const ERRORCONST = "-99999"
