# Generated by Django 4.0 on 2021-12-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='symbol',
        ),
        migrations.AddField(
            model_name='stock',
            name='PEG',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='stockList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.stocklist'),
        ),
    ]
