# Generated by Django 4.0 on 2021-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_remove_stock_eps_remove_stock_peg_remove_stock_roa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='EPS',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='PEG',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='ROA',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='ROE',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='bookValue',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='divPerShare',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='divYield',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='fiftyDayMovingAvg',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='forwardPE',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='priceToSales',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='pricesToBook',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='quarterEarningsGrowth',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='quarterRevenueGrowth',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='targetPrice',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='trailingPE',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='twoHundredDayMovingAvg',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='yearlyHigh',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='yearlyLow',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
