# Generated by Django 4.0 on 2021-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_stock_eps_stock_peg_stock_roa_stock_roe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='EBITDA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='companyName',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
