# Generated by Django 4.0 on 2021-12-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_stock_ebitda_stock_companyname_stock_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='pricesToBook',
            new_name='priceToBook',
        ),
    ]
