# Generated by Django 4.0 on 2021-12-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_rename_pricestobook_stock_pricetobook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='EBITDA',
        ),
    ]
